### ISSUE TITLE
Maven build requires version 4.3.0.Final

### ISSUE THREAD

**Issue by plutext** [ModeShape/quickstart#16]
Just a quick note that https://github.com/ModeShape/quickstart/commit/5f4a9e3ece866766af55407ab8351fc0e0f1056f breaks maven build by changing 

```
-    <version>4.3.0.Final</version>
+    <version>4.4-SNAPSHOT</version>
```
with

```
Non-resolvable import POM: Could not find artifact org.modeshape.bom:modeshape-bom-jbossas:pom:4.4-SNAPSHOT
```

**Comment by hchiorean** [comment]
not really: you're looking at `master` which is built & contains changes specific to the latest ModeShape `master` which is `4.4-SNAPSHOT`.
So either a) build locally ModeShape and only then build and quickstarts or b) use the `4.3.0.Final` tag.

**Comment by plutext** [comment]
My point is that checking out master then building with maven doesn't work out of the box, which I would've thought was a legitimate expectation.  As we agree if you don't build ModeShape first, you have to manually change the version. That makes things harder than it should be (especially since there is no 4.3.0.Final branch in the quickstart repo, and nothing that I saw to suggest the version needs to be changed)

(I'd been using docker to run jboss/modeshape, so not building ModeShape locally.  It would be nice if the quickstarts were also available for docker, then there'd be no need to build them on another machine and get them into the docker container somehow.)

**Comment by hchiorean** [comment]
this: https://github.com/ModeShape/quickstart/tree/4.3.0.Final is the tag for 4.3.0.Final you can use to build against the latest ModeShape release, which is available both in Nexus and Maven Central.

>My point is that checking out master then building with maven doesn't work out of the box, which I would've thought was a legitimate expectation.

I don't agree: since ModeShape doesn't release SNAPSHOT versions (and never has) `master` is always the latest "work in progress". Since the `quickstarts` and `main` repositories are separate and the `quickstarts` repository depends on the `main` repository, if you want to run the "latest" quickstarts it's perfectly acceptable that you first have to build the latest ModeShape (main) artifacts.
